site_name: Bot Discord Last War
site_description: Documentação completa do Bot Discord para Last War Survival
site_author: Calel
site_url: https://seu-usuario.github.io/bot-discord-lastwar/

# Repository
repo_name: calel95/bot_discord_lastwar
repo_url: https://github.com/calel95/bot_discord_lastwar

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    - toc.follow
    - content.code.annotate
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

# Extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - md_in_html

# Page tree
nav:
  - Home: index.md
  - Guia de Início Rápido:
    - quick-start/index.md
    - Instalação: quick-start/installation.md
    - Configuração: quick-start/configuration.md
    - Primeiro Uso: quick-start/first-use.md
  - Bot Discord:
    - bot/index.md
    - Comandos: bot/commands.md
    - Bot Tradutor: bot/translator.md
    - Personalização: bot/customization.md
  - Apache Airflow:
    - airflow/index.md
    - DAGs: airflow/dags.md
    - Monitoramento: airflow/monitoring.md
    - Troubleshooting: airflow/troubleshooting.md
  - APIs e Integrações:
    - apis/index.md
    - Gemini AI: apis/gemini.md
    - YouTube API: apis/youtube.md
    - Discord API: apis/discord.md
  - Desenvolvimento:
    - dev/index.md
    - Estrutura do Código: dev/structure.md
    - Testes: dev/testing.md
    - Contribuindo: dev/contributing.md
  - Deploy:
    - deploy/index.md
    - Docker: deploy/docker.md
    - Produção: deploy/production.md
    - Monitoramento: deploy/monitoring.md
  - FAQ: faq.md
  - Changelog: changelog.md

# Plugins
plugins:
  - search
  - mermaid2
  - git-revision-date-localized:
      enable_creation_date: true

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/calel95/bot_discord_lastwar
    - icon: fontawesome/brands/discord
      link: https://discord.gg/seu-servidor
  version:
    provider: mike

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js